spring:
  application:
    name: gateway
server:
  port: 5555
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

zuul:
  sensitive-headers: Cookie,Set-Cookie

security:
    oauth2:
      resource:
        token-info-uri: http://localhost:9191/oauth/check_token
      client:
        client-id: gateway-service
        client-secret: oauth-secret
logging:
  level:
    root: ERROR


ribbon:
  eureka:
    enabled: true


