spring:
  application:
    name: user-service
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=linkdin
    username: sa
    password: Vivekdb@1
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    ddl-auto: update
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8085